### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_inspect'

### ISSUE THREAD

**Issue by mguyard** [pschmitt/jcalapi#317]
Hello,

In latest docker image (717f5be9690929f7bccbf81f446e05b8432feef697c27ba679c473a67b7b6e18) , i've this issue :

```
2024-06-10 15:15:35 WARNING:  Current configuration will not reload as not all conditions are met, please refer to documentation.
2024-06-10 15:15:35 Traceback (most recent call last):
2024-06-10 15:15:35   File "/app/jcalapi/run.py", line 81, in <module>
2024-06-10 15:15:35     main()
2024-06-10 15:15:35   File "/app/jcalapi/run.py", line 77, in main
2024-06-10 15:15:35     server.run()
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
2024-06-10 15:15:35     return asyncio.run(self.serve(sockets=sockets))
2024-06-10 15:15:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-10 15:15:35     return runner.run(main)
2024-06-10 15:15:35            ^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-10 15:15:35     return self._loop.run_until_complete(task)
2024-06-10 15:15:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
2024-06-10 15:15:35     await self._serve(sockets)
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
2024-06-10 15:15:35     config.load()
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
2024-06-10 15:15:35     self.loaded_app = import_from_string(self.app)
2024-06-10 15:15:35                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 22, in import_from_string
2024-06-10 15:15:35     raise exc from None
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-06-10 15:15:35     module = importlib.import_module(module_str)
2024-06-10 15:15:35              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-06-10 15:15:35     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-10 15:15:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 15:15:35   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-06-10 15:15:35   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-06-10 15:15:35   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-06-10 15:15:35   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-06-10 15:15:35   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-06-10 15:15:35   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/jcalapi/app.py", line 13, in <module>
2024-06-10 15:15:35     from fastapi_utils.tasks import repeat_every
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/fastapi_utils/__init__.py", line 4, in <module>
2024-06-10 15:15:35     from .cbv_base import Api, Resource, set_responses, take_init_parameters
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/fastapi_utils/cbv_base.py", line 5, in <module>
2024-06-10 15:15:35     from .cbv import INCLUDE_INIT_PARAMS_KEY, RETURN_TYPES_FUNC_KEY, _cbv
2024-06-10 15:15:35   File "/usr/local/lib/python3.11/site-packages/fastapi_utils/cbv.py", line 21, in <module>
2024-06-10 15:15:35     from typing_inspect import is_classvar
2024-06-10 15:15:35 ModuleNotFoundError: No module named 'typing_inspect'
```

**Comment by mguyard** [comment]
Addiing this in pyproject.toml works :

`typing_inspect = "^0.9.0"`
